name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checkout project code
      - uses: actions/checkout@v2

      # Install and run shellcheck for all shell scripts
      - run: sudo apt install shellcheck
      - run: for f in $(find scripts -type f -name *.sh); do shellcheck $f; done;

      # Use python setup action to configure version
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Run validation script
      - run: ./scripts/validate.sh
